### ISSUE TITLE
undefined method `create_resque_adapter'

### ISSUE THREAD

**Issue by leoplct** [virtualstaticvoid/taskinator#11]
**Describe the bug**
I am trying to run this simple process but I got this error. I am using sidekiq.

```
3.0.2 :003 > ReportsProcess.create_process().start!
2022-01-29T15:32:56Z 35588 TID-3zc INFO: Taskinator client with redis options {}
starting..
2022-01-29T15:32:56Z 35588 TID-3zc INFO: Completed task for process '8c93707e-c64e-4ef7-a395-f39eb8587627'. Pending is 2.
2022-01-29T15:32:56Z 35588 TID-3zc ERROR: The queue adapter `resque` is not yet supported or it's runtime isn't loaded.
/.rvm/gems/ruby-3.0.2/gems/taskinator-0.4.4/lib/taskinator/queues.rb:14:in `rescue in create_adapter': The queue adapter `resque` is not yet supported or it's runtime isn't loaded. (RuntimeError)
/.rvm/gems/ruby-3.0.2/gems/taskinator-0.4.4/lib/taskinator/queues.rb:12:in `create_adapter': undefined method `create_resque_adapter' for Taskinator::Queues:Module (NoMethodError)
Did you mean?  create_sidekiq_adapter
```

**To Reproduce**
```
module ReportsProcess
    extend Taskinator::Definition
  
    # when creating the process, supply the same arguments
    # that the DoSomeWork worker expects

    define_process do
        task :start
        task :middle
        task :end
    end

    def start
        puts "starting.."
    end

    def middle()
        puts "Download report:"
    end

    def end
        puts "ending..."
    end

end

ReportsProcess.create_process().start!
```

**Gemfile**
```
gem 'sidekiq', '~> 6.2.1'
gem 'taskinator'
```

**Comment by leoplct** [comment]
**config/initializer/taskinator.rb**

```
Taskinator.configure do |config|
    config.queue_adapter = :sidekiq
end
```
